// Package config turns ARClient's rule model into the two engine
// configurations that actually carry traffic: the xray core config, and (see
// zeptun.go) the zeptun TOML.
//
// The generators share every value they must agree on through model.Config, so
// the fakedns address range that xray answers from and the include list that
// zeptun installs are generated from one field. A desync there would not fail;
// it would send selected traffic out the physical NIC while every status
// indicator claimed it was tunnelled.
package config

import (
	"fmt"
	"sort"
	"strings"

	"arclient/internal/model"
)

// Outbound and inbound tags. Routing rules refer to these by string, and a rule
// naming a tag that no outbound declares makes the core refuse to start with an
// error that does not point at the typo, so they live in one place.
const (
	InboundTag   = "mixed-in"
	TagBlock     = "block"
	TagDirectTCP = "tcp-direct"
	TagDirectUDP = "udp-direct"
	TagDNS       = "dns-out"
	TagFragTLS   = "frag-tls"
	TagFragPlain = "frag-plain"
	TagFragUDP   = "frag-udp"
	TagTunnel    = "tunnel"
)

// ListenAddr is the loopback address both local listeners bind to.
//
// Aether's SOCKS5 has no authentication, so loopback is the only thing keeping
// other processes on the machine out of the tunnel. It must never be widened to
// 0.0.0.0.
const ListenAddr = "127.0.0.1"

// DefaultFakednsPoolSize bounds the domain-to-address mapping cache.
//
// It is not optional and not cosmetic. The core's fake DNS pool refuses to
// start unless both a pool and a size are set, and the size is what it uses to
// size the LRU, so omitting it produces a core that loads its configuration
// without complaint and then fails to start with "invalid fakeDNS setting" —
// an error that names neither the field nor the cause.
const DefaultFakednsPoolSize = 65535

// Options are per-run knobs that do not belong in the persisted model.
type Options struct {
	// LogLevel is the core's loglevel field.
	LogLevel string
	// AccessLog, when non-empty, turns on access logging to that path. Domain
	// discovery depends on it, and it is noisy enough that it stays off
	// otherwise.
	AccessLog string
	// DNSLog turns on resolver logging. Used by discovery to catch poisoned
	// answers that never reach the routing layer.
	DNSLog bool
}

// Generate builds the xray core configuration.
//
// It validates its inputs and returns an error rather than emitting a config the
// core would reject: a config that fails at startup is a bad debugging session,
// because the symptom looks identical to a filtering problem.
func Generate(cfg *model.Config, opts Options) (*XrayConfig, error) {
	if cfg == nil {
		return nil, fmt.Errorf("config: nil config")
	}
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("config: %w", err)
	}
	prof, ok := cfg.ActiveProfile()
	if !ok {
		return nil, fmt.Errorf("config: profile %q not found", cfg.Profile)
	}
	if len(opts.LogLevel) == 0 {
		opts.LogLevel = "warning"
	}
	pool, err := cfg.FakednsPrefix()
	if err != nil {
		return nil, fmt.Errorf("config: %w", err)
	}

	// Domain buckets, each disjoint by construction because a rule resolves to
	// exactly one effective mode. A domain can still appear in two buckets if
	// the user listed it under two rules with different modes; Conflicts()
	// reports that, and the ordering below makes tunnel win.
	fragDomains := cfg.EnabledDomains(model.ModeFrag, model.TransportBoth)
	fragTCP := cfg.EnabledDomains(model.ModeFrag, model.TransportTCP)
	fragUDP := cfg.EnabledDomains(model.ModeFrag, model.TransportUDP)
	tunnelDomains := cfg.EnabledDomains(model.ModeTunnel, model.TransportBoth)
	tunnelTCP := cfg.EnabledDomains(model.ModeTunnel, model.TransportTCP)
	tunnelUDP := cfg.EnabledDomains(model.ModeTunnel, model.TransportUDP)

	// The fakedns domain list is the union of everything the tunnel must
	// capture. It deliberately excludes direct rules: answering a direct
	// domain from the fake pool would put it in the tunnel, and the tunnel is
	// only supposed to carry what the user asked for.
	fakednsDomains := cfg.TunnelIncludes()

	out := &XrayConfig{
		Remarks: "generated by ARClient from profile " + prof.ID,
		Version: Version{Min: prof.VersionMin},
		Log: Log{
			LogLevel: opts.LogLevel,
			DNSLog:   opts.DNSLog,
			Access:   opts.AccessLog,
			Error:    "",
		},
		Policy: policy(prof),
		// The fake pool and the DNS resolvers live in the same document on
		// purpose: they are two halves of one decision, and separating them
		// across files is how they end up disagreeing.
		FakeDNS:   &FakeDNS{IPPool: pool.String(), PoolSize: DefaultFakednsPoolSize},
		DNS:       dns(fakednsDomains),
		Inbounds:  []Inbound{mixed(cfg.MixedPort)},
		Outbounds: outbounds(cfg, prof, fragTCP, fragUDP, tunnelDomains),
		Routing: Routing{
			DomainStrategy: "AsIs",
			Rules:          routingRules(cfg, fragTCP, fragUDP, tunnelTCP, tunnelUDP, len(fragDomains) > 0),
		},
	}
	return out, nil
}

// policy reproduces the source configs' lifetime limits. Level 12 exists so the
// DNS outbound can be given a much shorter idle timeout than user traffic,
// which keeps resolver state from accumulating over a long session.
func policy(_ model.Profile) Policy {
	return Policy{Levels: map[string]PolicyLevel{
		"0":  {UplinkOnly: 0, DownlinkOnly: 0},
		"12": {UplinkOnly: 0, DownlinkOnly: 0, ConnIdle: 12},
	}}
}

// ResolverFrontingHost is the address the unfiltered resolver is fronted onto,
// and ResolverBootstrapDomain is the matching fakedns entry that lets it
// bootstrap at all.
//
// The recursion this breaks: the resolver is DoH to cloudflare-dns.com, which is
// fronted onto challenges.cloudflare.com, and resolving that name needs a
// resolver, which is the DoH client, which needs to resolve cloudflare-dns.com.
// Without a fake answer for the fronting target the resolver can never start,
// every lookup times out, and nothing outside the fake pool resolves.
//
// The failure is camouflaged rather than obvious. Selected domains are answered
// from the fake pool without touching the network, so the rules the user
// configured keep working while every other destination silently hangs. It
// presents as a partial outage; it is a dead resolver.
const (
	ResolverFrontingHost    = "challenges.cloudflare.com"
	ResolverBootstrapDomain = "full:" + ResolverFrontingHost
)

// dns builds the resolver block.
//
// Three resolvers with different jobs:
//
//   - fakedns answers selected domains, plus the fronting target, from the fake
//     pool. That is what lets the routing rules match a domain on a connection
//     that arrived as an IP, and what lets zeptun capture by address range
//     without resolving anything.
//   - no-filter-dns is DoH to Cloudflare. It has to be DoH reached through
//     domain fronting, because plain DNS to a filtered resolver returns
//     poisoned answers and the fragment outbound would then connect to a
//     poisoned address.
//   - domestic-dns is the system resolver, kept for anything outside the
//     selected set.
//
// The pool itself is not here: it is the top-level fakedns key, because that is
// where the core reads it from.
func dns(fakednsDomains []string) DNS {
	d := DNS{
		// cloudflare-dns.com is itself filtered in Iran. The host override
		// makes the DoH request ride on a reachable address while still
		// carrying a certificate valid for cloudflare-dns.com, which is what
		// keeps TLS verification working against the front.
		Hosts: map[string]string{
			"cloudflare-dns.com": ResolverFrontingHost,
		},
		QueryStrategy:  "UseSystem",
		UseSystemHosts: true,
		ServeStale:     true,
	}
	// The bootstrap entry is unconditional and comes first. It is the one
	// fakedns entry that is not a user rule, and dropping it on the grounds
	// that "fakedns should only cover selected domains" is exactly the
	// mistake that leaves every unselected destination unresolvable.
	domains := make([]string, 0, len(fakednsDomains)+1)
	domains = append(domains, ResolverBootstrapDomain)
	for _, d := range fakednsDomains {
		if d != ResolverBootstrapDomain {
			domains = append(domains, d)
		}
	}
	fakednsDomains = domains
	d.Servers = []DNSServer{
		{Address: "fakedns", Domains: fakednsDomains},
		{
			Tag:       "no-filter-dns",
			Address:   "https://cloudflare-dns.com/dns-query",
			TimeoutMs: 12000,
			// FinalQuery stops other resolvers also answering, which would
			// otherwise let a poisoned answer win the race.
			FinalQuery: true,
		},
		{
			Tag:        "domestic-dns",
			Address:    "localhost",
			Domains:    fakednsDomains,
			TimeoutMs:  12000,
			FinalQuery: true,
		},
	}
	return d
}

// mixed builds the loopback mixed HTTP+SOCKS5 inbound.
func mixed(port int) Inbound {
	return Inbound{
		Tag:      InboundTag,
		Listen:   ListenAddr,
		Port:     port,
		Protocol: "mixed",
		Sniffing: &Sniffing{
			Enabled: true,
			// "fakedns" maps a fake address back to its domain, "tls" reads
			// the SNI. Both are required: without the first, a fakedns
			// connection is opaque; without the second, a connection to a real
			// address has no name to match a rule against.
			DestOverride: []string{"fakedns", "tls", "http", "quic"},
			// false lets the sniffed domain replace the dial target, so a
			// connection that arrived as an address still connects by name.
			RouteOnly: false,
		},
		Settings: InboundSettings{UDP: true},
		Stream: &StreamSettings{
			Sockopt: &Sockopt{
				// Discord's gateway is a long-lived WebSocket and the local
				// NAT drops idle TCP. These two settings are what keep it
				// connected. Removing them produces a client that connects and
				// then reports "Disconnected" minutes later, which reads as a
				// flaky client rather than a config change. The generator test
				// asserts they survive generation.
				TCPKeepAliveInterval: intp(1),
				TCPKeepAliveIdle:     intp(11),
			},
		},
	}
}

// outbounds builds every egress path the routing rules can select.
func outbounds(cfg *model.Config, prof model.Profile, fragTCP, fragUDP, tunnelDomains []string) []Outbound {
	he := HappyEyeballs{
		TryDelayMs:       prof.HappyEyeballs.TryDelayMS,
		PrioritizeIPv6:   prof.HappyEyeballs.PrioritizeIPv6,
		Interleave:       prof.HappyEyeballs.Interleave,
		MaxConcurrentTry: prof.HappyEyeballs.MaxConcurrentTry,
	}
	direct := func(tag, strategy string) Outbound {
		return Outbound{
			Tag:      tag,
			Protocol: "direct",
			Stream: &StreamSettings{
				Sockopt: &Sockopt{
					// ForceIP, not AsIs: the fragment chain is built around
					// the bytes of a TLS ClientHello, and resolving per
					// connection would change the timing and length of the
					// first flight unpredictably.
					DomainStrategy: strategy,
					HappyEyeballs:  &he,
				},
			},
		}
	}

	list := []Outbound{
		{Tag: TagBlock, Protocol: "block"},
		direct(TagDirectTCP, "ForceIP"),
		direct(TagDirectUDP, "ForceIPv4v6"),
		{
			Tag:      TagDNS,
			Protocol: "dns",
			Settings: &OutboundSettings{UserLevel: 12},
		},
		{
			// The primary path. Direct socket, TLS-bearing traffic fragmented
			// with the profile's finalmask chain. Keeps the real source IP.
			Tag:      TagFragTLS,
			Protocol: "direct",
			Stream: &StreamSettings{
				FinalMask: &FinalMask{TCP: fragmentLayers(prof.TCPTLS)},
				Sockopt:   &Sockopt{DomainStrategy: "ForceIP", HappyEyeballs: &he},
			},
		},
		{
			// Non-TLS TCP. Reached when sniffing cannot find a protocol and
			// the port is not 443, so a rule that has to work for a
			// non-HTTPS target still gets fragmented rather than dropped.
			Tag:      TagFragPlain,
			Protocol: "direct",
			Stream: &StreamSettings{
				FinalMask: &FinalMask{TCP: fragmentLayers(prof.TCP)},
				Sockopt:   &Sockopt{DomainStrategy: "ForceIP", HappyEyeballs: &he},
			},
		},
	}

	if len(fragUDP) > 0 {
		list = append(list, Outbound{
			Tag:      TagFragUDP,
			Protocol: "direct",
			Stream: &StreamSettings{
				FinalMask: &FinalMask{UDP: noiseLayers(prof)},
				Sockopt:   &Sockopt{DomainStrategy: "ForceIPv4v6"},
			},
		})
	}

	if len(tunnelDomains) > 0 {
		list = append(list, Outbound{
			Tag:      TagTunnel,
			Protocol: "socks",
			Settings: &OutboundSettings{
				Servers: []SocksServer{{
					Address: ListenAddr,
					Port:    cfg.AetherPort,
				}},
			},
		})
	}
	return list
}

// fragmentLayers converts profile steps into finalmask fragment layers.
func fragmentLayers(steps []model.FragmentStep) []FinalMaskLayer {
	out := make([]FinalMaskLayer, 0, len(steps))
	for _, s := range steps {
		out = append(out, FinalMaskLayer{
			Type: "fragment",
			Settings: FragmentSettings{
				Packets:  s.Packet,
				Lengths:  nonNil(s.Lengths),
				Delays:   nonNil(s.Delays),
				MaxSplit: s.MaxSplit,
			},
		})
	}
	return out
}

// noiseLayers converts the profile's UDP burst into a finalmask noise layer.
func noiseLayers(prof model.Profile) []FinalMaskLayer {
	if prof.UDPNoise == nil || len(prof.UDPNoise.Noise) == 0 {
		return nil
	}
	n := make([]noisePulse, 0, len(prof.UDPNoise.Noise))
	for _, p := range prof.UDPNoise.Noise {
		n = append(n, noisePulse{Random: p.Random, Delay: p.Delay})
	}
	return []FinalMaskLayer{{
		Type:     "noise",
		Settings: NoiseSettings{Reset: prof.UDPNoise.Reset, Noise: n},
	}}
}

// routingRules builds the ordered decision ladder.
//
// Order is the whole design, so it is spelled out rather than assembled
// incidentally:
//
//  1. ads, if enabled — first so nothing else can claim them
//  2. DNS interception, so queries never fall through to a direct rule
//  3. tunnel rules, before frag, so a domain listed under both modes is
//     tunnelled rather than fragmented
//  4. QUIC and UDP/443 blocked, scoped to frag domains only
//  5. frag rules
//  6. private and, when geo data is staged, Iranian addresses go direct
//  7. everything else goes direct
//
// Step 4 is the one that is easy to get wrong. The source configs block QUIC
// and UDP/443 globally; scoping that to frag domains is a deliberate change,
// because a global block would strip QUIC from unrelated traffic the user asked
// to leave alone. It is also the step that makes fragmentation do anything at
// all: a QUIC connection has no TLS ClientHello in it, so if the client
// negotiates QUIC the fragment chain never sees anything to split.
//
// Step 7 replaces the source configs' final block-everything rule. The
// requirement here is that unselected traffic is bypassed, and a connection
// routed to a direct outbound leaves with the real source address either way.
func routingRules(cfg *model.Config, fragTCP, fragUDP, tunnelTCP, tunnelUDP []string, hasFrag bool) []RoutingRule {
	var rules []RoutingRule

	if cfg.BlockAds && cfg.WithGeo {
		rules = append(rules, RoutingRule{
			OutboundTag: TagBlock,
			Domain:      []string{"geosite:category-ads-all"},
		})
	}

	// Resolver traffic has to be claimed before any of the domain rules, or a
	// query for a selected domain would match that domain's rule and be sent
	// through a fragment chain that is meant for application data.
	rules = append(rules, RoutingRule{OutboundTag: TagDNS, Port: "53"})

	// The resolver's own outbound traffic.
	//
	// The unfiltered resolver is DoH to cloudflare-dns.com, reached through
	// domain fronting. That request is itself subject to the same inspection,
	// so it has to leave through a fragmented socket or it is reset and no
	// name ever resolves. Omitting this rule does not look like a DNS problem:
	// every selected domain is answered from the fake pool without touching the
	// network, so the rules that matter keep working while everything else
	// hangs on a resolution that never completes.
	rules = append(rules,
		RoutingRule{OutboundTag: TagDirectTCP, InboundTag: []string{"domestic-dns"}, Network: "tcp"},
		RoutingRule{OutboundTag: TagDirectUDP, InboundTag: []string{"domestic-dns"}, Network: "udp"},
	)
	if hasFrag {
		rules = append(rules, RoutingRule{
			OutboundTag: TagFragTLS, InboundTag: []string{"no-filter-dns"},
		})
	}

	if len(tunnelTCP) > 0 {
		rules = append(rules, RoutingRule{
			OutboundTag: TagTunnel, Network: "tcp", Domain: tunnelTCP,
		})
	}
	if len(tunnelUDP) > 0 {
		rules = append(rules, RoutingRule{OutboundTag: TagTunnel, Network: "udp", Domain: tunnelUDP})
	}

	if hasFrag {
		fragAny := unionDomains(fragTCP, fragUDP)
		rules = append(rules,
			RoutingRule{
				OutboundTag: TagBlock, Network: "udp", Protocol: []string{"quic"}, Domain: fragAny,
			},
			RoutingRule{
				OutboundTag: TagBlock, Network: "udp", Port: "443", Domain: fragAny,
			},
		)
	}
	if len(fragUDP) > 0 {
		rules = append(rules, RoutingRule{OutboundTag: TagFragUDP, Network: "udp", Domain: fragUDP})
	}
	if len(fragTCP) > 0 {
		rules = append(rules, RoutingRule{OutboundTag: TagFragTLS, Network: "tcp", Domain: fragTCP})
	}

	// Private ranges are spelled out as literal CIDRs rather than
	// geoip:private, so the default build needs no geo data at all. The
	// geoip:ir term is appended only when geo assets were staged, because
	// referencing a file that is not present makes the core fail to start.
	rules = append(rules, RoutingRule{
		OutboundTag: TagDirectTCP, Network: "tcp", IP: privateAndGeo(cfg),
	})
	rules = append(rules, RoutingRule{
		OutboundTag: TagDirectUDP, Network: "udp", IP: privateAndGeo(cfg),
	})

	// The bypass default. Anything not claimed above leaves directly, which
	// means it never touches a fragment chain and never leaves through the
	// tunnel.
	//
	// The rule carries no ip or domain condition, and that is load-bearing
	// rather than lazy. A proxy client hands the core a *hostname*, and with
	// domainStrategy AsIs the core does not resolve it, so an ip condition on
	// the catch-all matches nothing. Traffic then falls through to the first
	// outbound, which is block, and every unselected destination is refused.
	// That is the opposite of the requirement, and it is silent: the listed
	// rules keep working, so it presents as "only some things are broken".
	rules = append(rules, RoutingRule{
		OutboundTag: TagDirectTCP, Network: "tcp,udp",
	})
	return rules
}

// privateAndGeo returns the CIDR list for the "obviously local" direct rule.
func privateAndGeo(cfg *model.Config) []string {
	ips := []string{
		"127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16",
		"169.254.0.0/16", "::1/128", "fc00::/7", "fe80::/10",
	}
	if cfg.WithGeo {
		ips = append(ips, "geoip:ir")
	}
	return ips
}

// unionDomains merges sorted domain lists into one sorted, de-duplicated list.
func unionDomains(lists ...[]string) []string {
	seen := map[string]struct{}{}
	var out []string
	for _, l := range lists {
		for _, d := range l {
			if _, ok := seen[d]; ok {
				continue
			}
			seen[d] = struct{}{}
			out = append(out, d)
		}
	}
	return out
}

func intp(v int) *int { return &v }

func nonNil(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// Conflicts returns domains that resolve to more than one routing engine, which
// happens when the same target is listed under two rules with different modes.
//
// The generator resolves these deterministically rather than failing, so the UI
// has to surface them: the user believes both rules apply and only one does.
//
// Deliberately compared by effective mode and not by transport bucket. A single
// rule with transport "both" occupies both the tcp and udp buckets by design,
// and reporting that as a conflict would make the warning fire on every correct
// configuration and train the user to ignore it.
func Conflicts(cfg *model.Config) []string {
	engines := map[string]map[string]bool{}
	add := func(mode model.Mode, ds []string) {
		for _, d := range ds {
			if engines[d] == nil {
				engines[d] = map[string]bool{}
			}
			engines[d][string(mode)] = true
		}
	}
	add(model.ModeFrag, cfg.EnabledDomains(model.ModeFrag, model.TransportBoth))
	add(model.ModeTunnel, cfg.EnabledDomains(model.ModeTunnel, model.TransportBoth))

	var out []string
	for domain, modes := range engines {
		if len(modes) > 1 {
			names := make([]string, 0, len(modes))
			for m := range modes {
				names = append(names, m)
			}
			sort.Strings(names)
			out = append(out, fmt.Sprintf("%s is claimed by both %s; tunnel wins by ordering and the other is inert",
				domain, strings.Join(names, " and ")))
		}
	}
	sort.Strings(out)
	return out
}
