package config

// The zeptun half of the configuration.
//
// This is what makes TUN capture selective rather than a blanket default route,
// and it is the part that dissolves the TUN loop. zeptun's WFP strict-route
// filters permit exactly one process by application id — itself, resolved from
// GetModuleFileNameW(nullptr) with no option to add another — so the core's
// direct outbound is not exempt. With a blanket default route the core dials
// outward, Windows hands the packet to the TUN, zeptun hands it back to the
// core, and the connection never terminates.
//
// Routing only the fake address pool into the tunnel removes the possibility
// rather than detecting it: the core's direct traffic goes to a real address,
// that address is not in the include list, and it leaves by the physical NIC
// before any of this is consulted. The WFP permit for the core is still added as
// a safety net, because a loop here presents as a total outage with no useful
// error.

import (
	"fmt"
	"strconv"
	"strings"

	"arclient/internal/model"
)

// ZeptunOptions are the tunnelling parameters that are deployment choices
// rather than user rules.
type ZeptunOptions struct {
	// Interface is the physical NIC name. Recorded for the WFP safety net and
	// for the core's optional sockopt.interface pin. Empty means "do not pin",
	// which is the default: pinning breaks silently when the user moves
	// between wifi and ethernet.
	Interface string
	MTU       int
	Queues    int
	// SuppressResolveControl keeps zeptun from rewriting system DNS. ARClient
	// points Windows at the core's resolver instead, because the core is what
	// applies the fake pool and knows which domains are selected.
	SuppressResolveControl bool
}

// ZeptunTOML renders the zeptun configuration as TOML.
//
// The schema is small and fixed, so it is emitted directly rather than through
// a marshaller. That keeps the binary free of a TOML dependency and, more
// usefully, keeps the output diffable against zeptun's own conf/zeptun.toml.
func ZeptunTOML(cfg *model.Config, opts ZeptunOptions) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("zeptun: nil config")
	}
	if err := cfg.Validate(); err != nil {
		return "", fmt.Errorf("zeptun: %w", err)
	}
	pool, err := cfg.FakednsPrefix()
	if err != nil {
		return "", fmt.Errorf("zeptun: %w", err)
	}
	if opts.MTU == 0 {
		opts.MTU = 1500
	}

	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# Generated by ARClient. Do not edit by hand.")
	w("#")
	w("# route.include is the fake address pool the core answers from for")
	w("# selected domains. Routing only that pool is what keeps unselected")
	w("# traffic off the tunnel entirely, rather than letting it enter and")
	w("# then be sent back out by a direct rule.")
	w("")
	w("preset = %q", "desktop")
	w("log_level = %q", "warn")
	w("stats_interval_s = 0")
	w("")
	w("[tun]")
	w("name = %q", "arclient0")
	w("mtu = %d", opts.MTU)
	w("queues = %d", opts.Queues)
	w("address = [%q, %q]", "172.31.253.1/30", "fd7a:115c:a1e0::1/126")
	w("")
	w("[stack]")
	w("mode = %q", "userspace")
	w("udp_nat = %q", "endpoint_independent")
	w("icmp = %q", "auto")
	w("")
	w("[handler]")
	w("kind = %q", "socks5")
	w("")
	w("[handler.socks5]")
	// The core's mixed listener speaks SOCKS5 as well as HTTP, so the tunnel
	// terminates into the same listener the proxy capture mode uses. That is
	// the reason the core sits in front of Aether rather than behind it: the
	// core can still sniff a domain off a flow that arrived as an address.
	w("server = %q", fmt.Sprintf("%s:%d", ListenAddr, cfg.MixedPort))
	w("udp = true")
	w("udp_mode = %q", "udp")
	w("pool_size = 4")
	w("")
	w("[route]")
	w("auto_route = true")
	// Include-only routing. There is deliberately no catch-all default route:
	// that is the blanket case, and it is what creates the loop described
	// above.
	w("include = [%q]", pool.String())
	// The loopback range carries the core's own listeners, and routing it into
	// the tunnel would break the tunnel.
	w("exclude = [%q]", "127.0.0.0/8")
	if opts.Interface != "" {
		w("exclude_interface = [%q]", opts.Interface)
	}
	w("")
	w("[dns]")
	// The core owns resolution. It answers the fake pool for selected domains
	// and forwards the rest, and a second resolver in front of it would have to
	// duplicate that policy.
	w("fake_ip = false")
	w("hijack = false")
	w("systemd_resolved = false")
	if opts.Interface != "" {
		w("")
		w("# core interface pin (informational, applied by the core generator):")
		w("# interface = %q", opts.Interface)
	}
	return b.String(), nil
}

// TunnelIncludeList returns the address prefixes the tunnel must capture.
//
// It is exported so the WFP safety net and the selftest can assert against the
// same list the tunnel was actually started with, rather than recomputing it
// and hoping the two agree.
func TunnelIncludeList(cfg *model.Config) ([]string, error) {
	pool, err := cfg.FakednsPrefix()
	if err != nil {
		return nil, err
	}
	return []string{pool.String()}, nil
}

// FormatZeptunStats renders counter pairs for the selftest report.
func FormatZeptunStats(values map[string]uint64) string {
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	// Small, fixed set; ordering by key keeps output stable between runs so
	// two reports can be diffed.
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j] < keys[j-1]; j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	var b strings.Builder
	for _, k := range keys {
		b.WriteString("  " + k + ": " + strconv.FormatUint(values[k], 10) + "\n")
	}
	return b.String()
}
